/**
 * 前台
 * Next.js 的主架構（Root Layout）。
 * 
 * 最外層的佈局組件
 * 所有頁面的共同容器
 * 設定全域配置的地方
 * 此處勁量保持乾淨，只做必要的設定
 * 因為是 server component，所以不能使用 client-side 的 hooks
 */

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import QueryClientProvider from "@/providers/query-client-provider"
import "./globals.css";


// 1. 設定字體
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// 2. SEO metadata（會套用到所有頁面）
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 3. Root Layout - 主架構 server component 
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <QueryClientProvider> {/* 全域的 React Query 設定 */}
            {children} {/* 所有頁面內容都會渲染在這裡 */}
          </QueryClientProvider>
      </body>
    </html>
  );
}
